/**

-- Generated by ChatGPT - don't trust without review, refine as needed --


 * outputs.tf
 *
 * Exposes the key outputs from the firewall module:
 * - Resource group and location
 * - Public IP information (per firewall)
 * - Firewall object information (per firewall)
 * - Aggregated summary map of all firewalls
 */

# -------------------------------------------------------------------
# Resource group and location context
# -------------------------------------------------------------------

output "rgname" {
  description = "The resource group name used for all firewalls and public IPs."
  value       = var.rgname
}

output "location" {
  description = "The Azure region where all firewalls and public IPs are deployed."
  value       = var.location
}

# -------------------------------------------------------------------
# Public IP outputs
# -------------------------------------------------------------------

output "public_ip_ids" {
  description = "Map of public IP resource IDs, keyed by firewall name."
  value       = { for name, pip in azurerm_public_ip.fw_pip : name => pip.id }
}

output "public_ip_addresses" {
  description = "Map of assigned public IP addresses, keyed by firewall name."
  value       = { for name, pip in azurerm_public_ip.fw_pip : name => pip.ip_address }
}

output "public_ip_names" {
  description = "Map of public IP resource names, keyed by firewall name."
  value       = { for name, pip in azurerm_public_ip.fw_pip : name => pip.name }
}

# -------------------------------------------------------------------
# Firewall outputs
# -------------------------------------------------------------------

output "firewall_ids" {
  description = "Map of Azure Firewall resource IDs, keyed by firewall name."
  value       = { for name, fw in azurerm_firewall.fw : name => fw.id }
}

output "firewall_names" {
  description = "Map of Azure Firewall resource names, keyed by firewall name."
  value       = { for name, fw in azurerm_firewall.fw : name => fw.name }
}

output "firewall_private_ips" {
  description = "Map of private IPs assigned to each firewall, keyed by firewall name."
  value       = {
    for name, fw in azurerm_firewall.fw :
    name => fw.ip_configuration[0].private_ip_address
  }
}

# -------------------------------------------------------------------
# Aggregated summary output
# -------------------------------------------------------------------

output "firewalls_summary" {
  description = <<EOT
A map summarizing each firewall deployment, keyed by firewall name.
Each map value contains:
- firewall_id
- firewall_name
- private_ip_address
- public_ip_name
- public_ip_address
- resource_group_name
- location
EOT

  value = {
    for name, fw in azurerm_firewall.fw : name => {
      firewall_id         = fw.id
      firewall_name       = fw.name
      private_ip_address  = fw.ip_configuration[0].private_ip_address
      public_ip_name      = azurerm_public_ip.fw_pip[name].name
      public_ip_address   = azurerm_public_ip.fw_pip[name].ip_address
      resource_group_name = var.rgname
      location            = var.location
    }
  }
}
