/**

-- Generated by ChatGPT - don't trust without review, refine as needed --

 * outputs.tf
 *
 * Exposes useful information about the virtual network peerings created by this module.
 *
 * Outputs include:
 * - Individual peering IDs and names for both directions (A→B and B→A)
 * - A combined map of both peerings for easier iteration by consumers
 */

# -------------------------------------------------------------------
# Individual outputs
# -------------------------------------------------------------------

output "a_to_b_id" {
  description = "The resource ID of the virtual network peering from VNet A to VNet B."
  value       = azurerm_virtual_network_peering.a_to_b.id
}

output "a_to_b_name" {
  description = "The name of the virtual network peering from VNet A to VNet B."
  value       = azurerm_virtual_network_peering.a_to_b.name
}

output "b_to_a_id" {
  description = "The resource ID of the virtual network peering from VNet B to VNet A."
  value       = azurerm_virtual_network_peering.b_to_a.id
}

output "b_to_a_name" {
  description = "The name of the virtual network peering from VNet B to VNet A."
  value       = azurerm_virtual_network_peering.b_to_a.name
}

# -------------------------------------------------------------------
# Aggregated output
# -------------------------------------------------------------------

output "peerings" {
  description = <<EOT
A map summarizing both VNet peerings, keyed by direction (a_to_b, b_to_a).
Each map value contains the peering name and ID for that direction.
EOT

  value = {
    a_to_b = {
      id   = azurerm_virtual_network_peering.a_to_b.id
      name = azurerm_virtual_network_peering.a_to_b.name
    }
    b_to_a = {
      id   = azurerm_virtual_network_peering.b_to_a.id
      name = azurerm_virtual_network_peering.b_to_a.name
    }
  }
}
